### ISSUE TITLE
[macOS] Markblog executable points to non-existent file

### ISSUE THREAD

**Issue by filiphorvei** [olaven/markblog#59]
**Describe the bug**
Upon installing markblog with the command `deno install --allow-read --allow-write --name markblog https:denopkg.com/olaven/markblog`, an executable "markblog" is created in the `.deno/bin` folder.

This executable contains the following code:
```
#!/bin/sh
# generated by deno install
deno "run" "--allow-read" "--allow-write" "file:///Users/<macOS-username>/https:denopkg.com/olaven/markblog" "$@"
```

However, this file it's attempting to run does not exist.

**To Reproduce**
1. Install markblog: `deno install --allow-read --allow-write --name markblog https:denopkg.com/olaven/markblog`
2. Add `.deno/bin` to the PATH if not added already
3. Try to run any command with `markblog`

**Additional context**
OS: macOS Catalina 10.15.5
Deno version 1.3.1
Terminal: zsh 5.7.1 (default Apple install)

**Comment by filiphorvei** [comment]
Update:

The issue is fixed by simply removing the file:///Users/<macOS-username>/ from the executable, so the file looks like this:

```
#!/bin/sh
# generated by deno install
deno "run" "--allow-read" "--allow-write" "https:denopkg.com/olaven/markblog" "$@"
```

Seems like it's a Deno issue then...

**Comment by olaven** [comment]
I believe I have solved this 🎉 
The installation instructions in `README.md` (and therefore also in your installation 😕) contains an error. 
Replace `https:denopkg.com/olaven/markblog` with `https://denopkg.com/olaven/markblog`. (`https:`/`https://`)

I'll update the documentation! 👍 Thanks 😄
